// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_021.DataBase;

namespace project_021.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20200602154031_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("project_021.Models.Post", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<Guid?>("TopicID");

                    b.HasKey("ID");

                    b.HasIndex("TopicID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("project_021.Models.Topic", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsEnabled");

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("project_021.Models.Post", b =>
                {
                    b.HasOne("project_021.Models.Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicID");
                });
#pragma warning restore 612, 618
        }
    }
}
